# Generated by Django 3.2.9 on 2021-12-03 20:26

from django.db import migrations

from authapp.models import ShopUser, ShopUserProfile


def create_shopuser_profile(apps, schema_editor):

    #     Не понимаю почему тут получаю:
    #     for user in users:
    # TypeError: 'ModelBase' object is not iterable
    #
    #     users = apps.get_model('authapp', 'ShopUser')
    #     users_profile = apps.get_model('authapp', 'ShopUserProfile')

    users = ShopUser.objects.all()
    for user in users:
        if not user.shopuserprofile:
            ShopUserProfile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_shopuserprofile'),
    ]

    operations = [
        migrations.RunPython(create_shopuser_profile),
    ]



